/**
 * THE FILE. What actually leaves this product when a dealer needs to attach something to an email.
 *
 * =====================================================================================================
 * THE DEFECT THIS CLOSES. The four deliverables rendered as a <pre> block on a web page with a
 * provenance table under them. There was no download, no print, no file. On a Monday with a
 * solicitation closing at 3pm Eastern, a wall of labelled text on a screen is not something you can
 * send to a buyer, so the operator retyped it into an email and every caveat stayed behind on the page.
 *
 * =====================================================================================================
 * THE RULE THAT SHAPES EVERY LINE BELOW: A DOWNLOADED ARTIFACT THAT HAS SHED ITS CAVEATS IS WORSE THAN
 * NO DOWNLOAD, BECAUSE IT WILL BE FORWARDED.
 * =====================================================================================================
 * The screen can afford to put an abstention in a panel further down, because the reader can scroll
 * back. A file cannot: it is read once, by somebody who never saw the screen, and often by somebody
 * deciding whether to award. So everything the on-screen version showed travels in the file, in this
 * order and never optionally:
 *
 *   1. WHAT THIS FILE IS, and the one thing it is not: a submission. Nothing here transmits.
 *   2. THE PROVENANCE STRIP. The feed day the workspace was serving, the source archive and its
 *      digest, the generating build, and the instant of generation.
 *   3. THE STATE OF EVERY DELIVERABLE, computed, including the ones that are not ready and why.
 *   4. THE ARTIFACT BODIES, byte for byte as the screen rendered them.
 *   5. EVERY FIGURE'S SOURCE, one row each.
 *   6. WHAT WAS CARRIED IN rather than typed, with the sentence that came with it.
 *   7. EVERY ABSTENTION: unread facts, cannot-assess findings, refused renders, unquotable rules.
 *
 * A section with nothing in it prints a sentence saying it is empty and why. It is never dropped,
 * because a missing heading reads as a heading that did not apply.
 *
 * PLAIN TEXT ON PURPOSE. Markdown, which is plain text that survives being pasted into an email, read
 * in a terminal, or opened in anything. No PDF: this build has no typesetter, and a hand-rolled PDF
 * layout would be a fabricated document shape dressed as an official one. Print to paper is the
 * paper path, and it is a real stylesheet on real letter paper.
 *
 * No clock and no IO. The caller passes the instant and the provenance.
 */

import type { DocumentsView } from './view-model'
import type { DeliverableKind } from './artifacts'
import type { ReconciledCarry } from './prefill'
import { documentFingerprint, type ReproductionVerdict } from './saved-document'

export type FeedProvenance =
  | {
      readonly known: true
      readonly feed_day: string
      readonly archive_key: string
      readonly archive_sha256: string
    }
  | { readonly known: false; readonly why: string }

export type DocumentFileInput = {
  /** ISO 8601, from the caller's injected clock. */
  readonly generated_at: string
  /** The running build, so a file can be traced to the code that made it. Null when unstamped. */
  readonly build_commit: string | null
  readonly feed: FeedProvenance
  readonly view: DocumentsView
  readonly carried: readonly ReconciledCarry[]
  readonly reproduction: ReproductionVerdict
  /** Who is signed in, so a forwarded file names its operator. Null when the session is anonymous. */
  readonly operator: string | null
}

export type ComposedFile = {
  readonly filename: string
  readonly media_type: string
  readonly content: string
}

const RULE = '='.repeat(94)
const THIN = '-'.repeat(94)

function slug(s: string): string {
  const cleaned = s.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase()
  return cleaned === '' ? 'unidentified' : cleaned
}

function dateStamp(iso: string): string {
  const d = iso.slice(0, 10).replace(/-/g, '')
  return /^\d{8}$/.test(d) ? d : 'undated'
}

function provenanceBlock(i: DocumentFileInput): string[] {
  const out: string[] = []
  out.push('PROVENANCE OF THIS FILE')
  out.push(THIN)
  out.push(`Generated at              ${i.generated_at}`)
  out.push(`Generated by build        ${i.build_commit === null ? 'not stamped in this environment' : i.build_commit}`)
  out.push(`Operator                  ${i.operator === null || i.operator.trim() === '' ? 'not recorded for this session' : i.operator}`)
  if (i.feed.known) {
    out.push(`Government feed day       ${i.feed.feed_day}`)
    out.push(`Source archive            ${i.feed.archive_key}`)
    out.push(`Source archive sha256     ${i.feed.archive_sha256}`)
  } else {
    out.push('Government feed day       NOT READ IN THIS ENVIRONMENT')
    out.push(`Why                       ${i.feed.why}`)
    out.push(
      'What that means           No figure in this file was carried from the government feed. Every',
    )
    out.push(
      '                          value below was entered by an operator or is fixed template text.',
    )
  }
  out.push(`Document fingerprint      ${documentFingerprint(i.view)} (FNV-1a 64, a change detector, not a signature)`)
  return out
}

function reproductionBlock(r: ReproductionVerdict): string[] {
  if (r.kind === 'not_a_reproduction') return []
  const out: string[] = ['', 'AS-OF NOTICE', THIN]
  out.push(r.headline)
  out.push(r.detail)
  if (r.kind === 'drifted') {
    for (const d of r.differences) out.push(`  - ${d}`)
  }
  return out
}

function deliverableBlock(view: DocumentsView): string[] {
  const out: string[] = ['', 'THE FOUR DELIVERABLES, AND THE STATE EACH ONE IS ACTUALLY IN', THIN]
  if (view.deliverables.length === 0) {
    out.push('No lot is captured, so no deliverable has a state. Nothing stands in for one.')
    return out
  }
  for (const d of view.deliverables) {
    out.push('')
    out.push(`${d.label.toUpperCase()}  [${d.state_label}]`)
    out.push(`  Stock number: ${d.subtitle}`)
    out.push(`  ${d.statement}`)
    out.push(`  Next: ${d.next_action}`)
    for (const m of d.missing) out.push(`  Missing ${m.ref}, ${m.label}`)
  }
  return out
}

function artifactBlock(view: DocumentsView, only: DeliverableKind | null): string[] {
  const artifacts = only === null ? view.artifacts : view.artifacts.filter((a) => a.kind === only)
  const out: string[] = ['', 'THE ARTIFACTS', THIN]
  if (artifacts.length === 0) {
    out.push(
      'No artifact was assembled. A deliverable with no template in this build, or one whose render was',
    )
    out.push('refused, produces nothing here rather than an empty document with gaps in it.')
    return out
  }
  for (const a of artifacts) {
    out.push('')
    out.push(RULE)
    out.push(a.label.toUpperCase())
    out.push(RULE)
    if (a.view.ok) {
      out.push('')
      out.push(a.view.body.trimEnd())
      out.push('')
      out.push('  EVERY FIGURE ABOVE, AND WHERE IT CAME FROM')
      for (const f of a.view.provenance) {
        out.push(`    {{${f.ref}}}  ${f.value}    ${f.source}`)
      }
    } else {
      out.push('')
      out.push('  THIS ARTIFACT REFUSED TO RENDER. It is not included, because a federal document with a')
      out.push('  gap where a figure belongs is not a draft, it is an artifact that must not exist.')
      for (const r of a.view.refusals) out.push(`    - ${r}`)
      out.push(`  ${a.view.explanation}`)
    }
  }
  return out
}

function carriedBlock(carried: readonly ReconciledCarry[]): string[] {
  const out: string[] = ['', 'WHAT WAS CARRIED IN RATHER THAN TYPED', THIN]
  if (carried.length === 0) {
    out.push('Nothing was carried in. Every value in this document was entered by an operator by hand.')
    return out
  }
  out.push('A carried value came from a measured record rather than from a person. Each one is named')
  out.push('here with its source and whether the operator changed it.')
  for (const c of carried) {
    out.push('')
    out.push(`  ${c.what}  [${c.provenance}, ${c.status}]`)
    out.push(`    ${c.statement}`)
    if (c.needs_confirmation && c.status === 'unchanged') {
      out.push('    THIS FIGURE HAS NOT BEEN CONFIRMED BY A PERSON as the operator\'s own.')
    }
  }
  return out
}

function abstentionBlock(view: DocumentsView): string[] {
  const out: string[] = ['', 'WHAT THIS FILE DOES NOT SAY', THIN]
  let any = false

  if (view.classification !== null) {
    out.push('')
    out.push(`  Compliance path: ${view.classification.path_label}`)
    out.push(`  Material category: ${view.classification.category}`)
    out.push(
      `  Provenance rung: ${
        view.classification.provenance_rung === null
          ? 'none satisfied'
          : `rung ${view.classification.provenance_rung}`
      }`,
    )
    for (const r of view.classification.reasons) out.push(`    ${r.statement} (deciding field: ${r.deciding_field})`)
    if (view.classification.rung_gap !== null) out.push(`    ${view.classification.rung_gap}`)
    for (const b of view.classification.blocked_facts) {
      any = true
      out.push(`    UNREAD FACT, ${b.field}: ${b.statement} ${b.next_action}`)
    }
    if (view.classification.rule_labels.length > 0) {
      out.push(`    Rules applied: ${view.classification.rule_labels.join(' | ')}`)
    }
  }

  if (view.preflight !== null) {
    out.push('')
    out.push(`  Zero-rejection pre-flight: ${view.preflight.verdict_label}`)
    if (view.preflight.clear_statement !== null) out.push(`    ${view.preflight.clear_statement}`)
    for (const f of view.preflight.findings) {
      any = true
      out.push(`    ${f.severity === 'blocking' ? 'BLOCKING' : 'CANNOT ASSESS'}, ${f.check}: ${f.statement}`)
      out.push(`      failing field: ${f.failing_field}`)
      if (f.quote !== null) {
        out.push(`      quoted from ${f.quote_attribution}: "${f.quote}"`)
      } else {
        out.push(
          `      The exact wording of ${f.quote_attribution} is not verified in the primary source, so it`,
        )
        out.push('      is described rather than quoted.')
      }
      if (f.reroute !== null) out.push(`      Instead: ${f.reroute}`)
    }
  }

  if (view.quarantined_rules.length > 0) {
    any = true
    out.push('')
    out.push('  RULES THIS BUILD MAY NOT QUOTE YET')
    for (const r of view.quarantined_rules) out.push(`    ${r.identifier}. ${r.why}`)
  }

  if (!any) {
    out.push('')
    out.push('  Nothing was abstained from on this lot. Every fact the classifier and the pre-flight')
    out.push('  needed was captured, and every rule cited has been read in its primary source.')
  }
  return out
}

function header(title: string, nsn: string): string[] {
  return [
    RULE,
    `ONLYSOURCE  ${title.toUpperCase()}`,
    `Stock number ${nsn === '' ? 'not captured' : nsn}`,
    RULE,
    '',
    'THIS IS A WORKING DOCUMENT PRODUCED BY ONLYSOURCE. IT IS NOT A SUBMISSION.',
    'Nothing in this product transmits anything to a government system. A quote reaches DLA when a',
    'person uploads it. Read every figure below against the source before you act on it.',
    '',
  ]
}

function footer(): string[] {
  return [
    '',
    THIN,
    'END OF FILE. Every figure above resolves to a stored value listed with its source, and every',
    'abstention the on-screen version showed is reproduced here. If a caveat is missing from this file',
    'that is a defect in ONLYSOURCE, not a fact about the lot.',
  ]
}

/** The whole packet: every deliverable, every artifact, every caveat, one file. */
export function composePacketFile(i: DocumentFileInput): ComposedFile {
  const nsn = i.view.deliverables[0]?.subtitle ?? ''
  const lines: string[] = [
    ...header('document packet', nsn),
    ...provenanceBlock(i),
    ...reproductionBlock(i.reproduction),
    ...deliverableBlock(i.view),
    ...artifactBlock(i.view, null),
    ...carriedBlock(i.carried),
    ...abstentionBlock(i.view),
    ...footer(),
  ]
  return {
    filename: `onlysource-packet-${slug(nsn)}-${dateStamp(i.generated_at)}.md`,
    media_type: 'text/markdown;charset=utf-8',
    content: lines.join('\n') + '\n',
  }
}

/**
 * THE REST OF THE PACKET, on a single-deliverable download.
 *
 * =====================================================================================================
 * THIS BLOCK EXISTS BECAUSE THE SUITE CAUGHT ITS ABSENCE, and the defect was exactly the one this
 * module was written to prevent. `composeArtifactFile` filtered the artifact list to the requested
 * kind, which also filtered out every OTHER deliverable's refusal, so a quote packet downloaded on its
 * own shed the fact that the counter-offer memo would not render. The enumerate-every-abstention test
 * failed and named the missing sentence.
 *
 * It is not padding. The quote packet's own fixed text names the traceability packet as its enclosure,
 * so a reader holding the quote alone genuinely needs to know that the enclosure it cites could not be
 * built. The states of the other three deliverables are the shortest honest way to say that.
 * =====================================================================================================
 */
function restOfPacketBlock(view: DocumentsView, only: DeliverableKind): string[] {
  const others = view.deliverables.filter((d) => d.kind !== only)
  const out: string[] = ['', 'THE REST OF THE PACKET THIS DOCUMENT BELONGS TO', THIN]
  if (others.length === 0) {
    out.push('No other deliverable has a state, because no lot is captured.')
    return out
  }
  out.push('These are not attached. Their states are here because this document may cite them.')
  for (const d of others) {
    out.push('')
    out.push(`  ${d.label}  [${d.state_label}]`)
    out.push(`    ${d.statement}`)
    for (const m of d.missing) out.push(`    Missing ${m.ref}, ${m.label}`)
    const artifact = view.artifacts.find((a) => a.kind === d.kind)
    if (artifact !== undefined && !artifact.view.ok) {
      out.push('    That deliverable refused to render:')
      for (const r of artifact.view.refusals) out.push(`      - ${r}`)
    }
  }
  return out
}

/**
 * One deliverable on its own, for the case a buyer asked for exactly one thing.
 *
 * IT CARRIES THE SAME PROVENANCE AND THE SAME ABSTENTIONS AS THE WHOLE PACKET. A per-artifact download
 * is the most likely thing to be forwarded on its own, so trimming the caveats out of it would be
 * precisely the failure this module exists to prevent.
 */
export function composeArtifactFile(kind: DeliverableKind, i: DocumentFileInput): ComposedFile {
  const row = i.view.deliverables.find((d) => d.kind === kind)
  const nsn = row?.subtitle ?? ''
  const label = row?.label ?? kind.replace(/_/g, ' ')
  const lines: string[] = [
    ...header(label, nsn),
    ...provenanceBlock(i),
    ...reproductionBlock(i.reproduction),
    '',
    'THE STATE OF THIS DELIVERABLE',
    THIN,
    row === undefined
      ? 'This deliverable has no computed state, because no lot is captured.'
      : `${row.label}  [${row.state_label}]\n  ${row.statement}\n  Next: ${row.next_action}`,
    ...(row === undefined ? [] : row.missing.map((m) => `  Missing ${m.ref}, ${m.label}`)),
    ...artifactBlock(i.view, kind),
    ...restOfPacketBlock(i.view, kind),
    ...carriedBlock(i.carried),
    ...abstentionBlock(i.view),
    ...footer(),
  ]
  return {
    filename: `onlysource-${slug(label)}-${slug(nsn)}-${dateStamp(i.generated_at)}.md`,
    media_type: 'text/markdown;charset=utf-8',
    content: lines.join('\n') + '\n',
  }
}
